### ISSUE TITLE
Manila export_locations issue

### ISSUE THREAD

**Issue by kustikov112** [sapcc/manila#262]
Hello,
Looks like after the latest terraform provider update, something is happened with the export_locations feature for Manila shares. 

Using terraform provider 3.0.0 everything worked pretty fine. Requests were made against https://share-3.eu-de-2.cloud.sap/v2/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations endpoint. 

BUt with 3.1.0, terraform using https://share-3.eu-de-2.cloud.sap/v1/c627a1c98e31449490ba740fb2ce8afb/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations, which is leading to errors, on attempts to get export locations. 

Not sure, it looks like something to be with this Aliases - https://github.com/gophercloud/gophercloud/blob/df5faf8f12e1bf88c1b959510798a673779cb0b7/endpoint_search.go#L48

They bumped the version of gophercloud 2.1 -> 2.7 here https://github.com/terraform-provider-openstack/terraform-provider-openstack/releases/tag/v3.1.0

Issue may be solved by adding 
```
provider "openstack" {
  endpoint_overrides = {
  "sharev2" = "https://share-3.eu-de-2.cloud.sap/v2/"
  }
}
```

But it looks like rather a workaround to the issue. 
Error logs:
```
2025-05-27T07:22:06.249Z [ERROR] provider.terraform-provider-openstack_v3.1.0: Response contains error diagnostic: @module=sdk.proto diagnostic_severity=ERROR tf_resource_type=openstack_sharedfilesystem_share_v2 @caller=github.com/hashicorp/terraform-plugin-go@v0.27.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_detail="" diagnostic_summary="Failed to retrieve share's export_locations 8d03ad8f-3515-42f1-ad08-9095a8a3d743: Expected HTTP response code [200] when accessing [GET https://share-3.eu-de-2.cloud.sap/v1/c627a1c98e31449490ba740fb2ce8afb/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations], but got 404 instead: {\"message\": \"The resource could not be found.<br /><br />\n\n\n\", \"code\": \"404 Not Found\", \"title\": \"Not Found\"}" tf_proto_version=5.9 tf_provider_addr=registry.terraform.io/terraform-provider-openstack/openstack tf_req_id=a6f250f1-0d73-ade7-fda4-002ae31ab346 tf_rpc=ReadResource timestamp=2025-05-27T07:22:06.249Z
2025-05-27T07:22:06.249Z [ERROR] vertex "openstack_sharedfilesystem_share_v2.shared_backup" error: Failed to retrieve share's export_locations 8d03ad8f-3515-42f1-ad08-9095a8a3d743: Expected HTTP response code [200] when accessing [GET https://share-3.eu-de-2.cloud.sap/v1/c627a1c98e31449490ba740fb2ce8afb/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations], but got 404 instead: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}
2025-05-27T07:22:06.249Z [ERROR] vertex "openstack_sharedfilesystem_share_v2.shared_backup (expand)" error: Failed to retrieve share's export_locations 8d03ad8f-3515-42f1-ad08-9095a8a3d743: Expected HTTP response code [200] when accessing [GET https://share-3.eu-de-2.cloud.sap/v1/c627a1c98e31449490ba740fb2ce8afb/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations], but got 404 instead: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}
```

**Comment by Carthaca** [comment]
[This](https://github.com/gophercloud/gophercloud/issues/3347) is being fixed in https://github.com/gophercloud/gophercloud/pull/3351

**Comment by kustikov112** [comment]
Can't confirm. 
Tried open stack 3.1.0 to 3.3.0. 
Still the same
`Error: Failed to retrieve share's export_locations 8d03ad8f-3515-42f1-ad08-9095a8a3d743: Expected HTTP response code [200] when accessing [GET https://share-3.eu-de-2.cloud.sap/v1/c627a1c98e31449490ba740fb2ce8afb/shares/8d03ad8f-3515-42f1-ad08-9095a8a3d743/export_locations], but got 404 instead: {"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}`
